/* ============================================
   English locale (en-US)
   Mounted to window.I18N_EN_US for non-module loading
   Notes:
   - Computer-science terms (HTML / CSS / API / SDK / SQL / etc.) keep their original form
   - All visible UI strings are translated
   ============================================ */
window.I18N_EN_US = {
  // Common
  "common.confirm": "OK",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.loading": "Loading…",
  "common.search": "Search",
  "common.export": "Export",
  "common.import": "Import",
  "common.empty": "No data",
  "common.yes": "Yes",
  "common.no": "No",
  "common.required": "Required",
  "common.search.keyword": "Search by ID or name",
  "common.reset": "Reset",
  "common.previous": "Previous",
  "common.back": "Back",
  "common.next": "Next",
  "common.question": "Q {no}",
  "common.score": "{n} pts",
  "common.minutes": "{n} min",
  "common.minute": "min",
  "common.total": "Total {n}",
  "common.collapse": "Collapse",
  "common.expand": "Expand",

  // Navigation
  "nav.dashboard": "Dashboard",
  "nav.students": "Students",
  "nav.papers": "Papers",
  "nav.exam": "Exams",
  "nav.monitor": "Monitor",
  "nav.grading": "Grading",
  "nav.results": "Results",
  "nav.logout": "Logout",
  "nav.language": "Language",
  "lang.zh": "ZH",
  "lang.en": "EN",

  // Login
  "login.welcome": "LAN Exam System",
  "login.chooseRole": "Please choose your role",
  "login.student": "Student Login",
  "login.teacher": "Teacher Login",
  "login.studentId": "Student ID",
  "login.password": "Password",
  "login.username": "Username",
  "login.submit": "Sign In",
  "login.back": "Back",
  "login.studentIdPlaceholder": "Enter your student ID",
  "login.passwordPlaceholder": "Enter your password",
  "login.passwordHint": "Initial password: last 5 digits of your student ID",
  "login.footerHint": "Contact your invigilator if you have any problem",
  "login.brandTagline": "Secure · Stable · Efficient",
  "login.confirmWrong": "Wrong info",
  "login.confirmRight": "Confirmed",

  // Confirm name
  "confirm.title": "Please confirm your name",
  "confirm.desc": "We recognized you as:",
  "confirm.unknownName": "Unknown",

  // Exam list (student)
  "examList.title": "Please choose an exam",
  "examList.noExam": "No exam available",
  "examList.status.notStarted": "Not started",
  "examList.status.ongoing": "Ongoing",
  "examList.status.waiting": "Waiting",
  "examList.status.running": "Running",
  "examList.status.ended": "Ended",
  "examList.status.submitted": "Submitted",
  "examList.status.available": "Available",
  "examList.status.locked": "No attempts left",
  "examList.status.answering": "Answering",
  "examList.status.confirmed": "Instructions confirmed",
  "examList.status.finished": "Completed",
  "examList.status.retryable": "Retryable",
  "examList.status.loggedIn": "Instructions pending",
  "examList.remaining": "{n} attempt(s) left",
  "examList.unlimited": "Unlimited attempts",
  "examList.start": "Start",
  "examList.resume": "Resume",
  "examList.retry": "Retry",
  "examList.view": "View",
  "examList.locked": "Locked",
  "examList.lastScore": "Last score: {score}",
  "examList.notOpen": "Exam is not open",
  "examList.attemptInfo": "Used {used} / {max}",
  "examList.duration": "Duration: {n} min",
  "examList.paper": "Paper: {title}",

  // Instructions
  "instructions.title": "Instructions",
  "instructions.examName": "Exam name",
  "instructions.examDuration": "Duration",
  "instructions.totalScore": "Total score",
  "instructions.questionCount": "Question count",
  "instructions.rules": "Rules",
  "instructions.rule1": "Once started, the timer counts down and the exam is auto-submitted when time is up",
  "instructions.rule2": "Answers are auto-saved every 30 seconds, you can resume after an unexpected close",
  "instructions.rule3": "Do not switch tabs or minimize the window during the exam",
  "instructions.rule4": "A reminder will appear during the last 5 minutes",
  "instructions.rule5": "Please review before submitting. You cannot modify after submission",
  "instructions.agree": "I have read the instructions",
  "instructions.start": "Start exam",
  "instructions.pleaseAgree": "Please confirm you have read the instructions",
  "instructions.backToList": "Back to exam list",

  // Exam taking
  "exam.title": "Candidate",
  "exam.remaining": "Time left",
  "exam.submit": "Submit",
  "exam.submitConfirmTitle": "Confirm submission",
  "exam.submitConfirmMsg": "You have <strong style=\"color:var(--danger)\">{left}</strong> unanswered question(s) ({done}/{total}). Submit anyway?",
  "exam.confirmSubmit": "Submit",
  "exam.continueAnswering": "Continue",
  "exam.autoSubmit": "All answered. Submitting…",
  "exam.saved": "Auto-saved",
  "exam.qNav": "Questions",
  "exam.legendDone": "Answered",
  "exam.legendUndone": "Unanswered",
  "exam.legendCurrent": "Current",
  "exam.progress": "Progress",
  "exam.fillBlankPlaceholder": "Your answer",
  "exam.fillBlankHint": "Please fill in the blanks in order",
  "exam.tabSwitch.warn": "Tab switch detected {count}/{limit}. You will be force-submitted at {limit}.",
  "exam.tabSwitch.violation": "Tab switched {count} times. Exam force-submitted and invalidated.",
  "exam.examTimeUp": "Time is up. Auto-submitted.",
  "exam.alreadySubmitted": "You have submitted this exam",
  "exam.teacherForceSubmitted": "Force-submitted by teacher. Returning to list…",

  // Submitted
  "submitted.title": "Submitted",
  "submitted.desc": "Your answers have been submitted. Please wait for the result.",
  "submitted.examName": "Exam name",
  "submitted.time": "Submitted at",
  "submitted.backToList": "Back to list",
  "submitted.close": "Close",

  // Teacher dashboard
  "dashboard.title": "Dashboard",
  "dashboard.students": "Students",
  "dashboard.answering": "Answering",
  "dashboard.submitted": "Submitted",
  "dashboard.questions": "Questions",
  "dashboard.statusChart": "Status distribution",
  "dashboard.progressChart": "Answer progress",
  "dashboard.scoreChart": "Score distribution",
  "dashboard.realtime": "Live",
  "dashboard.loggedIn": "{n} logged in",
  "dashboard.progress.0": "Not started",
  "dashboard.progress.1to3": "1-3 done",
  "dashboard.progress.4to6": "4-6 done",
  "dashboard.progress.all": "All done",

  // Students
  "students.title": "Students",
  "students.importBtn": "Import students",
  "students.templateBtn": "Template",
  "students.listTitle": "Student list",
  "students.total": "{n} student(s) in total",
  "students.colId": "Student ID",
  "students.colName": "Name",
  "students.colClass": "Class",
  "students.colAccount": "Account",
  "students.colInitialPwd": "Initial password",
  "students.empty": "No students yet. Please import first.",
  "students.rulesTitle": "Account rules",
  "students.rule1": "Account = student ID; initial password = last 5 digits of the student ID",
  "students.rule2": "Supports Excel batch import with columns: ID / Name / Class",
  "students.rule3": "Re-importing the same ID will update name, class and password",
  "students.templateDownloaded": "Template downloaded",
  "students.imported": "{n} student(s) imported",
  "students.modalTitle": "Import students",
  "students.modalHint": "Supports .xlsx / .xls. The first row is the header",
  "students.modalExcelCols": "Excel columns: ID | Name | Class",

  // Papers
  "papers.title": "Papers",
  "papers.listTitle": "Paper list",
  "papers.colId": "Paper ID",
  "papers.colTitle": "Title",
  "papers.colTotalScore": "Total",
  "papers.colDuration": "Duration",
  "papers.colQuestionCount": "Questions",
  "papers.createBtn": "Create paper",
  "papers.importBtn": "Import paper",
  "papers.templateBtn": "Template",
  "papers.importSuccess": "Imported {n} question(s)",
  "papers.importErrors": "Import failed: {reason}",
  "papers.modalTitle": "Import paper",
  "papers.modalSupport": "Supports Excel / JSON / Markdown",
  "papers.modalExcelCol": "Excel columns: No | Type | Stem | Options | Answer | Score | Keywords | Blank count",
  "papers.templateFormatExcel": "Excel template",
  "papers.templateFormatJson": "JSON template",
  "papers.templateFormatMd": "Markdown template",

  // Exam admin
  "examAdmin.title": "Exams",
  "examAdmin.currentExam": "Current exam",
  "examAdmin.createBtn": "Create exam",
  "examAdmin.startExam": "Start",
  "examAdmin.examRunning": "Running",
  "examAdmin.endExam": "End",
  "examAdmin.resetExam": "Reset to Pending",
  "examAdmin.resetAllExams": "Reset All",
  "examAdmin.resetExamForId": "Reset exam #{id} to ‘Pending’? This clears start/end time but keeps student records.",
  "examAdmin.resetAllExamsConfirm": "Reset all non-pending exams to ‘Pending’? Student records are not affected.",
  "examAdmin.checkDuration": "Check time",
  "examAdmin.startExamForId": "Start exam #{id}? It will become visible to students immediately.",
  "examAdmin.endExamForId": "End exam #{id}? All unsubmitted students will be force-submitted.",
  "examAdmin.viewPaper": "View paper",
  "paperView.totalQuestions": "{n} question(s) in total",
  "paperView.totalScore": "Total score: {n}",
  "paperView.empty": "No questions in this paper",
  "paperView.answer": "Answer",
  "paperView.keywords": "Keywords",
  "examAdmin.examList": "Exam list",
  "examAdmin.totalExams": "{n} exam(s) in total",
  "examAdmin.colNo": "No.",
  "examAdmin.colName": "Name",
  "examAdmin.colPaper": "Paper",
  "examAdmin.colDuration": "Duration",
  "examAdmin.colStatus": "Status",
  "examAdmin.colCreatedAt": "Created at",
  "examAdmin.colMaxAttempts": "Attempts",
  "examAdmin.colActions": "Actions",
  "examAdmin.actionMonitor": "Monitor",
  "examAdmin.actionResults": "Results",
  "examAdmin.actionEdit": "Edit",
  "examAdmin.actionDelete": "Delete",
  "examAdmin.empty": "No exams yet",
  "examAdmin.modalCreateTitle": "Create exam",
  "examAdmin.modalEditTitle": "Edit exam",
  "examAdmin.fieldName": "Exam name",
  "examAdmin.fieldPaper": "Paper",
  "examAdmin.fieldDuration": "Duration (min)",
  "examAdmin.fieldMaxAttempts": "Max attempts",
  "examAdmin.maxAttemptsHint": "Default 1; 0 means unlimited",
  "examAdmin.maxAttemptsEditHint": "Only affects students who have not started yet",
  "examAdmin.createSuccess": "Exam created",
  "examAdmin.updateSuccess": "Exam updated",
  "examAdmin.deleteSuccess": "Exam deleted",
  "examAdmin.deleteConfirm": "Delete this exam? This cannot be undone.",
  "examAdmin.durationExpire": "Time is up. Exam ended and force-submitted.",
  "examAdmin.durationExpireForced": "Time is up. Force-submitted {n} student(s).",
  "examAdmin.remainingMinutes": "Running, {n} min left",
  "examAdmin.notRunning": "Not running",

  // Monitor
  "monitor.title": "Live Monitor",
  "monitor.selectExam": "Select exam",
  "monitor.latest": "Latest (default)",
  "monitor.totalStudents": "Total",
  "monitor.loggedIn": "Logged in",
  "monitor.answering": "Answering",
  "monitor.submitted": "Submitted",
  "monitor.notLoggedIn": "Not logged in",
  "monitor.colId": "Student ID",
  "monitor.colName": "Name",
  "monitor.colStatus": "Status",
  "monitor.colProgress": "Progress",
  "monitor.colActions": "Actions",
  "monitor.forceSubmit": "Force submit",
  "monitor.submittedHint": "Submitted",

  // Grading
  "grading.title": "Grading",
  "grading.colNo": "#",
  "grading.colStudentId": "Student ID",
  "grading.colName": "Name",
  "grading.colClass": "Class",
  "grading.colObjective": "Objective",
  "grading.colSubjective": "Subjective",
  "grading.colTotal": "Total",
  "grading.colStatus": "Status",
  "grading.colSubmitTime": "Submitted at",
  "grading.colActions": "Actions",
  "grading.btnGrade": "Grade",
  "grading.btnView": "View",
  "grading.selectExam": "Select exam",
  "grading.allExams": "All exams",
  "grading.statusAll": "All",
  "grading.statusPending": "Pending",
  "grading.statusGraded": "Graded",
  "grading.sortBy": "Sort by",
  "grading.sortStudentId": "Student ID",
  "grading.sortScore": "Score",
  "grading.sortTime": "Submit time",
  "grading.sortName": "Name",
  "grading.asc": "Asc",
  "grading.desc": "Desc",
  "grading.pendingCount": "{n} pending",
  "grading.empty": "No short answers to grade",
  "grading.noExam": "No submissions in this exam",
  "grading.selectExamHint": "Please select an exam first",
  "grading.qaShortAnswer": "Short answer",
  "grading.qaFillBlank": "Fill in the blanks",
  "grading.answerLabel": "Student answer",
  "grading.answerEmpty": "Not answered",
  "grading.blankScores": "Per-blank score",
  "grading.gradeSaved": "Score saved",
  "grading.fullyGraded": "Graded",
  "grading.pending": "Pending",

  // Teacher - Results
  "results.title": "Results",
  "results.exportExcel": "Export Excel",
  "results.exportCsv": "Export CSV",
  "results.exportScope": "Export scope",
  "results.scopeAllClasses": "All classes",
  "results.scopeClass": "Class: {cls}",
  "results.average": "Average",
  "results.highest": "Highest",
  "results.lowest": "Lowest",
  "results.passRate": "Pass rate",
  "results.colClass": "Class",
  "results.colStudentId": "Student ID",
  "results.colName": "Name",
  "results.colObjective": "Objective",
  "results.colSubjective": "Subjective",
  "results.colTotal": "Total",
  "results.colRank": "Rank",
  "results.colStatus": "Status",
  "results.colSubmitTime": "Submit time",
  "results.allClasses": "All classes",
  "results.selectExam": "Select exam",
  "results.allExams": "All exams",
  "results.empty": "No results yet",

  // Status
  "status.notLoggedIn": "Not logged in",
  "status.loggedIn": "Logged in",
  "status.confirmed": "Confirmed",
  "status.answering": "Answering",
  "status.submitted": "Submitted",
  "status.forced": "Force-submitted",
  "status.waiting": "Waiting",
  "status.running": "Running",
  "status.ended": "Ended",
  "status.not_logged_in": "Not logged in",
  "status.logged_in": "Logged in",

  // Errors
  "error.AUTH_FAILED": "Session expired, please sign in again",
  "error.NAME_MISMATCH": "Name confirmation failed",
  "error.NO_EXAM_AVAILABLE": "No exam available",
  "error.EXAM_NOT_FOUND": "Exam not found",
  "error.EXAM_NOT_OPEN": "Exam is not open",
  "error.NO_ATTEMPTS_LEFT": "No attempts left",
  "error.EXAM_NOT_STARTED": "Teacher hasn't started this exam. Please refresh after the teacher enables it.",
  "error.RECORD_NOT_FOUND": "Record not found",
  "error.ALREADY_SUBMITTED": "Already submitted",
  "error.INVALID_MAX_ATTEMPTS": "Max attempts must be 0-99",
  "error.EXAM_NAME_REQUIRED": "Exam name is required",
  "error.PAPER_REQUIRED": "Please choose a paper",
  "error.PAPER_NOT_FOUND": "Paper not found",
  "error.FILE_REQUIRED": "Please choose a file",
  "error.UNSUPPORTED_FORMAT": "Unsupported file format",
  "error.PARSE_ERROR": "Parse error: {reason}",
  "error.VALIDATION_FAILED": "Validation failed",
  "error.FORCE_SUBMITTED": "Force-submitted by teacher",
  "error.NETWORK": "Network error, please retry",
  "error.EXAM_HAS_RECORDS": "Exam has submissions, cannot delete",
  "error.OPENPYXL_MISSING": "openpyxl not installed",
  "error.UNKNOWN": "Operation failed, please retry",

  // Question types
  "type.single_choice": "Single Choice",
  "type.multiple_choice": "Multiple Choice",
  "type.true_false": "True/False",
  "type.short_answer": "Short Answer",
  "type.fill_blank": "Fill in the Blanks",
  "type.programming": "Programming",

  // Options
  "option.true": "True",
  "option.false": "False",
};
